name: Build and Deploy React + Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to main
  pull_request:
    branches:
      - main  # Optional: deploy on PR merge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci  # Faster, reproducible installs

      - name: Build project
        run: npm run build  # Generates the 'dist' folder

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: /dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: /dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Authentication
          publish_dir: dist  # Correct key for deployment
