name: Build and Deploy React + Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployment from
  pull_request:
    branches:
      - main  # Optional: deploy when a PR is merged into main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Specify the Node.js version you need

    - name: Install dependencies
      run: |
        npm ci  # Uses package-lock.json for faster, reproducible installs

    - name: Build project
      run: |
        npm run build  # Runs the Vite build command to create the dist/ folder

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the deploy step runs after the build step

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        folder: dist  # Folder to deploy (Vite output folder)
        token: ${{ secrets.all_access }}  # Uses the all_access token for deployment