name: Mirror to bg-frontend

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Mirror to bg-frontend
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote add bg-frontend https://github.com/4w4i5/bg-frontend.git
          git config --global url."https://${GH_TOKEN}@github.com".insteadOf "https://github.com"
          git push bg-frontend --all
          git push bg-frontend --tags
name: Mirror to bg-frontend

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Mirror to bg-frontend
        env:
          GH_TOKEN: ${{ secrets.all_access }}
        run: |
          git remote add bg-frontend https://github.com/4w4i5/bg-frontend.git
          git config --global url."https://${GH_TOKEN}@github.com".insteadOf "https://github.com"
          git push bg-frontend --all
          git push bg-frontend --tags
